### ISSUE TITLE
V Chat Room is frozen.

### ISSUE THREAD

**Issue by erikkonstas** [DJMcMayhem/V#12]
Can you make a new chat-room please?

**Comment by DJMcMayhem** [comment]
The V chat room is frozen cause V only has one user right now, so nobody ever wants to talk about it. This is unfortunate, but it's just something we'll have to live with because we're using SE chat rooms. 

Do you want to talk about V? You can always ping me in [The Nineteenth Byte](http://chat.stackexchange.com/rooms/240/the-nineteenth-byte), or if you *really* want to use the V room, you could ask a mod to unfreeze it. I don't really feel like getting it unfrozen myself because it'll only get frozen again.
