### ISSUE TITLE
Source of slowness

### ISSUE THREAD

**Issue by potato44** [DJMcMayhem/V#21]
According to [Stasoid at PPCG](https://codegolf.stackexchange.com/a/138479/69655)(in the comments) the source of the slowness of V is the key_stroke() function in v.py. It includes a 100ms wait.

**Comment by DJMcMayhem** [comment]
Hmm. I remember this being necessary at one point because otherwise it would cause timing issues (where new keys would be processed before the old keys had finished, causing unpredictable behavior) but I can't think of any examples so I can see if this is still needed. I'll try to look into this more. It would be really really nice to not sleep between keys.

**Comment by DJMcMayhem** [comment]
The original issue was first found [in this chat conversation](https://chat.stackexchange.com/transcript/message/31917124#31917124). I'll start looking for what exactly in that is causing issues, and how to fix it without sleeping.

**Comment by DJMcMayhem** [comment]
Closed in https://github.com/DJMcMayhem/V/commit/aced470fad746a90415ff2144efea660f0af75b8
