### ISSUE TITLE
Documentation!

### ISSUE THREAD

**Issue by DJMcMayhem** [DJMcMayhem/V#4]
There is no list of official commands. Currently the only place these are documented is in my brain. This would go well with a code-page.

**Comment by christianrondeau** [comment]
I second this issue :) At least some basic steps to build / run V (prerequisites, supported os), some simple usage examples and either a list of customizations or at least a link to the files containing customizations / commands to be aware of. 

More than golfing, just using vim for text processing seems interesting :)

**Comment by DJMcMayhem** [comment]
@christianrondeau  I'm glad to hear that someone else it interested in the language. :) Is there any particular question you have? Feel free to raise another issue if something is unclear or not working right. I would try to make some docs on running it, but I'm just about to do a pretty major rewrite, so I don't want to bother with that when I'll need to change it again.

**Comment by christianrondeau** [comment]
Mostly out of curiosity :) I am getting acquainted with PPCG (and I'm loving  it) as well as with Vim. I had an idea and I saw you did something very similar to what I had in mind. Not exactly the same though,  and I don't yet speak Pythonese, so I also started my own project : https://github.com/christianrondeau/autovim

The approach is different however, since I'm not using Python (makes it messier but a great learning experience) but rather only Vimscript and a very small bash script.

I was (and still am)  looking to learning from what you have done, and if you also provide tests, maybe participate. For now though, it's only for the fun of it!
